### ISSUE TITLE
Online learning with mini-batches?

### ISSUE THREAD

**Issue by gtmtg** [OpenANN/OpenANN#172]
Hi! I'm trying to use OpenANN for online reinforcement learning with mini-batches. Unfortunately, I wasn't able to find a ton of documentation for online learning, so I wanted to get some clarification on how I should implement this. What I'm currently doing is creating a ```DataStream``` to feed data to the network and setting both the __```cacheSize```__ of my ```DataStream``` and the __```batchSize```__ of my ```MBSGD``` optimizer to my training batch size.

Is this approach correct? In particular, do I need to use a ```DataStream``` for this (rather than just feeding the data to my network directly, as in most of the examples), and is the way I set the parameters for the stream and the optimizer correct?

Thanks so much! I love OpenANN, by the way—it's the most complete neural network library that I was able to find, and bonus points because it's based on Eigen (so it's optimized for ARM out of the box)!

**Comment by AlexanderFabisch** [comment]
Hi, an example for online learning with a DataStream can be found [here](https://github.com/OpenANN/OpenANN/blob/master/benchmarks/mnist/mnist.cpp#L85). So your idea seems to be correct. Let me know if you have any idea how we could improve the documentation. Thanks for the positive feedback. I'm always happy to here about successful applications.

**Comment by gtmtg** [comment]
@AlexanderFabisch Thanks for the quick response! I did see that example; I was confused by the fact that the ```cacheSize``` was set to ```loader.trainingN``` while the ```batchSize``` was always set to 1. Just to confirm, if I want to train in mini-batches, should I set both the ```cacheSize``` and ```batchSize``` to my mini-batch size?

**Comment by AlexanderFabisch** [comment]
Well, that depends on what you want to do...

In your case you probably want `batchSize` and `cacheSize` to be equal. That means each time your cache is full, you will make a weight update with `MBSGD` and "forget" the data.

If `batchSize < cacheSize`, you will wait until your cache is full and make `cacheSize / batchSize` updates. That means in a RL setting you collected data based on an outdated policy that you could have updated already based on more recent data.

**Comment by gtmtg** [comment]
@AlexanderFabisch Great, thanks for your help!

**Comment by AlexanderFabisch** [comment]
You are welcome.
