### ISSUE TITLE
random_shuffle and -std=c++17

### ISSUE THREAD

**Issue by wduminy** [OpenANN/OpenANN#182]
`std::random_shuffle` has been removed from c++17.  So when I use this library with a project that has `-std=c++17` I get a compile error.

I replaced `std::random_shuffle` with `std::shuffle` in the code and it seems fine. I can send you a pull request if you want to apply this change.

**Comment by AlexanderFabisch** [comment]
Hi, thanks for the info. Is it possible to make it compatible to C++ 17 and previous standards? A pull requests would be nice.

**Comment by wduminy** [comment]
I think discussion can now continue on the pull request #183

**Comment by AlexanderFabisch** [comment]
I will leave it open and it will be closed when the PR is merged.
