### ISSUE TITLE
Implement ZCA whitening transform and global contrast normalization data preprocessing for CIFAR dataset

### ISSUE THREAD

**Issue by AlexanderFabisch** [OpenANN/OpenANN#34]
That should increase the accuracy a little bit.

ZCA whitening: see page 48 of the technical report http://www.cs.toronto.edu/~kriz/learning-features-2009-TR.pdf

Global contrast normalization: substract by mean and devide by std. deviation (according to http://ai.stanford.edu/~ang/papers/nipsdlufl10-AnalysisSingleLayerUnsupervisedFeatureLearning.pdf 3.1.1)

**Comment by MartinThoma** [comment]
Was ZCA / GCN implemented in Python somewhere?

**Comment by AlexanderFabisch** [comment]
ZCA is implemented (see [here](https://github.com/OpenANN/OpenANN/blob/master/python/preprocessing.pxi#L53), [here](https://github.com/OpenANN/OpenANN/blob/master/OpenANN/ZCAWhitening.h), and [here](https://github.com/OpenANN/OpenANN/blob/master/src/ZCAWhitening.cpp)). There is no implementation of GCN.
